### ISSUE TITLE
Include `events` option in solve_ivp

### ISSUE THREAD

**Issue by SantiagoMorandi** [SciML/SciPyDiffEq.jl#24]
Hello, 

I always worked with scipy.integrate.solve_ivp with the `BDF` method to solve my ODEs, defining a termination event to stop the integration when a specific condition is met. I tried the same solver here implemented in Julia, but I noticed that the `events` argument is not defined. 

Would it be possible to include this option in the Julia solver?

**Comment by SantiagoMorandi** [comment]
Hi Chris, 

I tried to use the solvers you mentioned and the first times I had a bug in my code, now everything works faster and better with Julia. Thanks for the reply (and sorry for the disturb)!

**Comment by ChrisRackauckas** [comment]
No worries!
